wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.13.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1644936187
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      2:
      - 1
      - 5
      - 9
      - 11
      3:
      - 17
      4: 3.8.12
      5: 0.12.9
      6: 4.13.0
      8:
      - 5
